# Generated by Django 3.2 on 2024-10-25 23:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(message='Nombre invalido, solo letras.', regex='^[a-zA-Z ]*$')])),
                ('ciudad', models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(message='Nombre invalido, solo letras.', regex='^[a-zA-Z ]*$')])),
                ('campeonatos', models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(message='Nombre invalido, solo letras.', regex='^[a-zA-Z ]*$')])),
                ('conferencia', models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(message='Nombre invalido, solo letras.', regex='^[a-zA-Z ]*$')])),
                ('estadio', models.CharField(max_length=100)),
                ('colores', models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(code='invalid_nombre', message='Color invalido solo letras', regex='^[a-zA-Z ]+$')])),
                ('liga', models.CharField(max_length=100)),
            ],
        ),
    ]
